### ISSUE TITLE
Can we support jruby applications in the Ruby Paketo Buildpack?

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/ruby#10]
On top of MRI, jruby is a fairly popular ruby runtime that we've supported in the Ruby CF Buildpack. It would be great if we could support jruby in the Ruby buildpack.

We should also think about how we can support other runtimes such as Rubinius in the future.

**Comment by fg-j** [comment]
@paketo-buildpacks/ruby-maintainers This has been open for a good minute. Is this still a relevant feature request? What questions would you want to see answered in a thorough investigation of jruby support?

**Comment by sophiewigmore** [comment]
I think it's still a  relevant issue, but I think an investigation into user interest would be necessary to actually implement and adopt this into the language family. I can't see it getting prioritized unless we had some answers to those questions, or had a situation in which a user who wants this feature contributed it.

**Comment by robdimsdale** [comment]
Note - it might be worth tracking the mechanism for switching between Java application servers (e.g. Tomcat and Liberty) in https://github.com/paketo-buildpacks/rfcs/pull/145. Whatever interface is decided upon might be a good basis for switching between alternative `ruby` implementations.

**Comment by robdimsdale** [comment]
I think we should close this issue because we haven't received any feedback indicating we should implement this, and I think the complexity and increased support load is non-trivial.

If we receive feedback that adding support for alternatives to `mri` would be useful, we can revisit this issue.
