### ISSUE TITLE
Add Environment Variables Buildpack to Group Order

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/ruby#463]
We should consider adding the [Paketo Environment Variables Buildpack](https://github.com/paketo-buildpacks/environment-variables/) to the Ruby Language family buildpack so that users can define environment variables during build time to get set on the application image.

**Comment by ryanmoran** [comment]
This was completed in https://github.com/paketo-buildpacks/ruby/pull/528. Closing.
