### ISSUE TITLE
Whether to use yarn cli when running a Ruby app image?

### ISSUE THREAD

**Issue by genevieve** [paketo-buildpacks/ruby#465]
Hey there 👋 

I have a ruby app that I built with pack & this buildpack. It has a package.json with the following script:
```
"start": "yarn run server",
```

When I try to run this image, it fails with:
```
bash: yarn: command not found
```

Since yarn isn't installed in the image, should we be using something else to start the app?

**Comment by sophiewigmore** [comment]
I'm curious if you tried to pack build this app with the Ruby buildpack as well as the Nodejs buildpack, and the Buildplan buildpack as you mentioned in #464?

**Comment by genevieve** [comment]
This is a separate app than the one in #464 but also, I put this issue in the wrong repo. It belongs in the nodejs repo. 🤦‍♀️  I will move that over.
