### ISSUE TITLE
Nomination of @genevieve for contributor

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/ruby#496]
In keeping with the [Paketo Buildpacks Governance document](https://github.com/paketo-buildpacks/community/blob/main/GOVERNANCE.md), I would like to nominate @genevieve for contributor to the Ruby language family.

@genevieve has implemented the entirety of the [`rails-assets` buildpack](https://github.com/paketo-buildpacks/rails-assets) up to this point and has experience building and deploying non-trivial Rails applications on Kubernetes. These are significant contributions to the language family and deserving of the promotion to contributor.

**Comment by sophiewigmore** [comment]
+1

**Comment by ryanmoran** [comment]
Looks like we have unanimous support for this. Welcome to the contribution team @genevieve!
