### ISSUE TITLE
Add CA Certificates Buildpack to Group Ordering

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/ruby#511]
We should add the [CA Certificates Buildpack](https://github.com/paketo-buildpacks/ca-certificates) to each group in the buildpack. This buildpack will allow application developers to provide their own CA certificates and have them included in the root truststore at build and runtime.

**Comment by andymoe** [comment]
Working on this.

**Comment by andymoe** [comment]
Did not get to come back this in the afternoon. Still need to fix the ruby test app.

**Comment by sophiewigmore** [comment]
Confirmed that this issue has been resolved by https://github.com/paketo-buildpacks/ruby/pull/558:

1. Packaged the version of the buildpack in linked PR
2. `pack build rake_ca -b ../../../build/buildpackage.cnb` on the /testdata/rake_ca_cert app
3. Saw
```
Paketo CA Certificates Buildpack 2.1.0
  https://github.com/paketo-buildpacks/ca-certificates
  Launch Helper: Contributing to layer
    Creating /layers/paketo-buildpacks_ca-certificates/helper/exec.d/ca-certificates-helper
``` 
in the logs from pack building
4. Ran `docker run -it -p 8080:8080 -e PORT-8080 -e "SERVICE_BINDING_ROOT"="/bindings" --volume "$PWD"/binding:/bindings/ca-certificates rake_ca` 
5. Saw `Added 1 additional CA certificate(s) to system truststore`
6. Ran `curl --cert cert.pem --key key.pem --cacert ca.pem https://localhost:8080` from the testdata/rake_ca_cert/certs directory

7. Saw `Hello world, Authenticated User!`
8. Ran `curl https://localhost:8080`


9. Saw `curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html`
