### ISSUE TITLE
Add usage example to README

### ISSUE THREAD

**Issue by drnic** [paketo-buildpacks/ruby#55]
Could we add an example app + sample `pack` usage example to the readme, please?

**Comment by drnic** [comment]
To get puma buildpack to work, I used:

```
pack build solar-mgmt --buildpack gcr.io/paketo-community/ruby --builder gcr.io/paketo-buildpacks/builder:cflinuxfs3
```

**Comment by kvedurmu** [comment]
This is good feedback for something we could do in **all** of our repos. We have a pretty extensive [samples repo](https://github.com/paketo-buildpacks/samples) that provides usage information that we should link to in every buildpack (at least at a language family level).
