### ISSUE TITLE
Set RAILS_LOG_TO_STDOUT to true/1

### ISSUE THREAD

**Issue by genevieve** [paketo-buildpacks/ruby#567]
## What happened?

* What were you attempting to do?

Build a rails app that sends logs to stdout

* What did you expect to happen?

I expected `RAILS_LOG_TO_STDOUT` to be enabled so that our environment config could pick it up and use it to set the appropriate logger to direct logs to stdout for the container

* What was the actual behavior? Please provide log output, if possible.

It is not enabled, the logs were directed to a file

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.

* What buildpacks are you using? Please include versions.

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

## Checklist

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [ ] I have included steps for reproduction.

**Comment by fg-j** [comment]
@genevieve @paketo-buildpacks/ruby-maintainers This has been open for a bit. Is this still a need? Is there a workaround available?

**Comment by ryanmoran** [comment]
Its not a bug. Its a feature request. Users routinely need to set this environment variable so that they can have their logs streamed to `stdout` in the container rather than the default location of a file inside the container. The workaround is just to set that environment variable when starting the container, but they shouldn't need to as having the buildpack set it by default would be pretty obviously better.

**Comment by fg-j** [comment]
Makes sense.

Until the buildpack sets this environment variable, users can get this behaviour today by setting `BPE_RAILS_LOG_TO_STDOUT=true` in the build environment. This would ensure that `RAILS_LOG_TO_STDOUT=true` automatically when the container starts (see [docs](https://paketo.io/docs/howto/configuration/#image-embedded-environment-variables)).

**Comment by ryanmoran** [comment]
@robdimsdale I think this logic would go into the `rails-assets` buildpack. Its the most closely related, if not completely aligned with the intent of this feature.

We'll want to set this variable as a default using https://pkg.go.dev/github.com/paketo-buildpacks/packit/v2#Environment.Default. This would allow users to still override this value if needed.

**Comment by robdimsdale** [comment]
I'm probably not going to get to this just yet, so anyone else who is interested is welcome to pick it up!
