### ISSUE TITLE
Add support for openjdk when rjb gem is present

### ISSUE THREAD

**Issue by fbongiovanni29** [paketo-buildpacks/ruby#612]
## What happened?

Building a rails app w/rjb fails:

* What were you attempting to do?
Build a rails app
* What did you expect to happen?
Build successfully
* What was the actual behavior? Please provide log output, if possible.
Build failed:
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/layers/paketo-buildpacks_bundle-install/build-gems/ruby/2.6.0/gems/rjb-1.6.2/ext
/layers/paketo-buildpacks_mri/mri/bin/ruby -I
/layers/paketo-buildpacks_mri/mri/lib/ruby/2.6.0 -r
./siteconf20210609-134-18g0s92.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/layers/paketo-buildpacks_mri/mri/bin/$(RUBY_BASE_NAME)
extconf.rb:54:in `<main>': JAVA_HOME is not set. (RuntimeError)

extconf failed, exit code 1

Gem files will remain installed in
/layers/paketo-buildpacks_bundle-install/build-gems/ruby/2.6.0/gems/rjb-1.6.2
for inspection.
Results logged to
/layers/paketo-buildpacks_bundle-install/build-gems/ruby/2.6.0/extensions/x86_64-linux/2.6.0-static/rjb-1.6.2/gem_make.out

An error occurred while installing rjb (1.6.2), and Bundler cannot continue.
Make sure that `gem install rjb -v '1.6.2' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  fillable-pdf was resolved to 0.9.1, which depends on
    rjb

error: exit status 5
ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle: failed with status code: 145
```

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.
pack 0.19

* What buildpacks are you using? Please include versions.
gcr.io/paketo-buildpacks/ruby

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?
paketobuildpacks/builder:full

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?
Repo is private

* Steps to reproduce
Add rjb to Gemfile and run:
```
pack build gcr.io/bdt-eng-play/prism-buildpack --buildpack gcr.io/paketo-buildpacks/ruby \
  --builder paketobuildpacks/builder:full
```

Note: It appears a buildpack for openjdk is already available https://github.com/paketo-buildpacks/adopt-openjdk

## Checklist

* [x] I have included log output.
* [x] The log output includes an error message.
* [x] I have included steps for reproduction.

**Comment by arjun024** [comment]
@fbongiovanni29 Did you try building with both buildpacks?

`pack build <image> --buildpack gcr.io/paketo-buildpacks/adopt-openjdk --buildpack gcr.io/paketo-buildpacks/ruby`

**Comment by fbongiovanni29** [comment]
@arjun024 Yes, I got this error when I tried that:
```
> pack build gcr.io/bdt-eng-play/prism-buildpack --buildpack gcr.io/paketo-buildpacks/ruby --buildpack gcr.io/paketo-buildpacks/adopt-openjdk --builder paketobuildpacks/builder:full
full: Pulling from paketobuildpacks/builder
Digest: sha256:b975aabae42b9e7fb9358516aa9620271ddeee7fe15eabe06dda7f54a73851fa
Status: Image is up to date for paketobuildpacks/builder:full
full-cnb: Pulling from paketobuildpacks/run
Digest: sha256:4ca11970d0b7d8059ca9952660079781739ab6e561d40e1859671bda330ad8a4
Status: Image is up to date for paketobuildpacks/run:full-cnb
latest: Pulling from paketo-buildpacks/ruby
Digest: sha256:6f765726dd17b0ba39d77d95e972c0e3893811e4450277414bd7ef58156de385
Status: Image is up to date for gcr.io/paketo-buildpacks/ruby:latest
latest: Pulling from paketo-buildpacks/adopt-openjdk
Digest: sha256:c0fa35c496769f3ca46676f5526cd48d6dcfccbd5fd8caec7ee775265c12701d
Status: Image is up to date for gcr.io/paketo-buildpacks/adopt-openjdk:latest
===> DETECTING
ERROR: No buildpack groups passed detection.
ERROR: Please check that you are running against the correct path.
ERROR: failed to detect: no buildpacks participating
ERROR: failed to build: executing lifecycle: failed with status code: 100
```

**Comment by arjun024** [comment]
@fbongiovanni29 The order of the buildpacks matter. Also since ruby does not require jdk usually, you might have to use some mechanism to request jdk from the jdk buildpack. An example is the [build-plan buildpack](https://github.com/paketo-community/build-plan).
If you're going this method, you'll have to create a `plan.toml` at the root of the source code something like:
```
[[requires]]
  name = "jdk"
  
  [requires.metadata]
  build = true
  launch = true
```
Then try `pack build <image> -b gcr.io/paketo-buildpacks/adopt-openjdk -b gcr.io/paketo-buildpacks/ruby -b gcr.io/paketo-community/build-plan`

If you can provide a sample app, I can advise better.

**Comment by fbongiovanni29** [comment]
No need! That worked, thank you very much. It would still be nice if openjdk were automagically added on the presence of the rjb gem, is the particularly difficult to implement? If I can find the time I could open a PR if you'd be willing to accept it?

**Comment by arjun024** [comment]
@fbongiovanni29 I'm not very familiar with rjb. Is this a popular use case?

You should talk to the @paketo-buildpacks/ruby-maintainers about it.
They hangout in the [#ruby](https://paketobuildpacks.slack.com/messages/ruby) channel in the paketo slack as well.

**Comment by sophiewigmore** [comment]
Hey @fbongiovanni29, Paketo Ruby buildpack maintainer here 👋 .

Getting this to automatically work wouldn't be terribly difficult to implement. It might involve adding the JDK buildpack to the Ruby [language-family order groupings](https://github.com/paketo-buildpacks/ruby/blob/main/buildpack.toml), and the updates to one of the buildpacks in the language family to `require` JDK like you did when you added the [Build Plan buildpack](https://github.com/paketo-community/build-plan).

I think to actually get this into the buildpack it would be helpful to hear a bit more about the use case in a new issue (titled something like "Add JDK to the Ruby language family", maybe). I'd like to hear some more background and rationale about why this isn't a super narrow use case, and also hear if other folks in the community are looking for something like this.

**Comment by sophiewigmore** [comment]
@fbongiovanni29 apologies, I think the notification from your follow up got buried. I'm glad to hear your adoption of buildpacks is going well. Have you been able to make any progress on this issue? I don't know that another issue is necessary, rather understand how widespread this use case is. 

As a workaround, did you try the Build Plan buildpack option I mentioned in my last comment? Using a [Paketo buildpackless builder ](https://github.com/paketo-buildpacks/buildpackless-base-builder) might be helpful in achieving this.

**Comment by fbongiovanni29** [comment]
Apologies, foolishly overlooked the fact that fillable-pdf is only a development & test only dependency of ours. Therefore I can add the env var `BUNDLE_WITHOUT=test:development` to the build and it passes that step

**Comment by sophiewigmore** [comment]
@fbongiovanni29 Great! Is there anything in this issue that needs to be resolved still, or can it be closed out?

**Comment by sophiewigmore** [comment]
@fbongiovanni29 I'm closing this out for now, due to inactivity/ it seems like you found a workaround. Feel free to reopen it if this is still an issue for you!
