### ISSUE TITLE
New release to support Ruby 3.1.0

### ISSUE THREAD

**Issue by dirkjonker** [paketo-buildpacks/ruby#726]
I can't build Ruby 3.1 apps since version 0.10 of this buildpack still refers to mri buildpack 0.5.1. Version 0.6 of the mri buildpack has Ruby 3.1 support. This is already correctly referred to in the main branch, it's just missing a new release.

**Comment by sophiewigmore** [comment]
@dirkjonker thanks for pointing that out. Just released [v0.11.0](https://github.com/paketo-buildpacks/ruby/releases/tag/v0.11.0)
