### ISSUE TITLE
Support Jammy Jellyfish

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/ruby#793]
## Describe the Enhancement

Ultimately, we want to be able to build Ruby apps on top of the Paketo Jammy stacks. Currently, builds fail because buildpacks like `mri` don't have the Jammy stack listed in their supported stacks.

## Possible Solution

- Update `buildpack.toml` and dependencies to add `io.buildpacks.stacks.jammy` as a compatible stack
- https://github.com/paketo-buildpacks/node-engine/issues/487
- (If necessary) Recompile installed dependencies to work on Jammy 
- Add some integration tests that test the buildpack against Jammy

## Motivation

Part of https://github.com/paketo-buildpacks/builder-jammy-base/issues/1

**Comment by joshuatcasey** [comment]
At least the following list needs to be updated:

- [ ] https://github.com/paketo-buildpacks/bundle-install
- [ ] https://github.com/paketo-buildpacks/bundler
- [ ] https://github.com/paketo-buildpacks/mri
- [ ] https://github.com/paketo-buildpacks/passenger
- [ ] https://github.com/paketo-buildpacks/puma
- [ ] https://github.com/paketo-buildpacks/rackup
- [ ] https://github.com/paketo-buildpacks/rails-assets
- [ ] https://github.com/paketo-buildpacks/rake
- [ ] https://github.com/paketo-buildpacks/thin
- [ ] https://github.com/paketo-buildpacks/unicorn

**Comment by sophiewigmore** [comment]
https://github.com/paketo-buildpacks/ruby/releases/tag/v0.20.0 contains Jammy support
