### ISSUE TITLE
Assert that builds are reproducible

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/ruby#811]
## Describe the Enhancement

Builds with this buildpack should be reproducible, meaning given identical inputs, the SHAs of resulting buildpack-built images are the same. This means, for a given app, if I run:
```
pack build my-app -b paketo-buildpacks/ruby
```
and then run
```
pack build my-app-copy -b paketo-buildpacks/ruby
```
with the same source code and configurations, the resulting image SHAs should be the same.

Currently, builds are *not* reproducible because of SBOMs included in the final app image. See https://github.com/paketo-buildpacks/packit/issues/367 and https://github.com/paketo-buildpacks/packit/issues/368. But once those issues are resolved and a new version of packit has been released, we should expect that the buildpack builds are reproducible.

## Possible Solution

Add assertions to integration tests that show that two builds with the same inputs produce identical outputs.

## Motivation

Build reproducibility is a [selling point of CNBs](https://buildpacks.io/docs/features/reproducibility/) that we want to provide to Paketo buildpack users. We want to know if future implementation decisions compromise build reproducibility.

**Comment by ryanmoran** [comment]
The only piece of the Ruby buildpack keeping us from completing this item is the `rails-assets` buildpack. Unfortunately, getting Rails assets to play nicely appears to be exceedingly hard. Rails (specifically, the `sprockets` gem) appears to be making a number of changes to cache and mapping files. The differing files are entirely opaque as they are binary file formats. Understanding what has changed and why would be quite complicated. Until such time as the Rails core team revamps asset packaging to be more reproducible, we are likely out of luck.

**Comment by robdimsdale** [comment]
So it sounds like there's no more work we can do here, and instead we should document the known limitations. I'll take that responsibility and assign myself the issue.
