### ISSUE TITLE
Investigate setting `MALLOC_ARENA_MAX=2` in the buildpacks

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/ruby#816]
Per @fgrehm in Paketo Slack: https://paketobuildpacks.slack.com/archives/CURGNPSTE/p1660655481999109, we should investigate adding `MALLOC_ARENA_MAX=2` as a setting in the buildpacks. 

>:question: Hello folks! Would you be open to automagically setting MALLOC_ARENA_MAX=2 from one of the ruby buildpacks? looks like we [already do that](https://github.com/search?p=1&q=org%3Apaketo-buildpacks+MALLOC_ARENA_MAX&type=Code) for other buildpacks

> we've recently noticed that some of our apps were consuming insanely amounts of memory and came across these articles:
https://www.mikeperham.com/2018/04/25/taming-rails-memory-bloat/
https://www.speedshop.co/2017/12/04/malloc-doubles-ruby-memory.html
we've also found out that heroku [sets that as the default for new ruby apps](https://devcenter.heroku.com/changelog-items/1683), so I think it makes sense to have similar behavior for paketo buildpacks. attached you'll find some real world metrics, that second blue dotted line is when we set the env var for one of our apps in our internal platform

**Comment by fgrehm** [comment]
Hey @sophiewigmore! Did you folks have a chance to discuss this? :smile:

**Comment by fgrehm** [comment]
All good, tks! I've just noticed that the PR description did not include the screenshot I mentioned in slack, so here it is to save others some clicking :-)

![image](https://user-images.githubusercontent.com/81859/196542096-c389af8a-a828-4d4c-8d65-238cc409694c.png)

**Comment by robdimsdale** [comment]
I'm on board. Especially if we set this as the default which would enable users to override it if necessary.

I think this is a great issue for the community. @fgrehm if you (or your team) are interested in contributing this we can point you to the relevant areas of the code and the types of patterns (tests etc) we'd expect to see for this feature.

**Comment by fgrehm** [comment]
Thanks folks! I added a story to our backlog, hopefully we can get to it soon :crossed_fingers:

We'll probably only have time to start on it by next week, so between now and then feel free to share whatever pointers you feel is relevant, I'm becoming more and more familiar with the code but it might not be me the one to grab it :smile:

**Comment by robdimsdale** [comment]
Sounds great!

I'd start by adding the following to the MRI buildpack's build phase (in [build.go](https://github.com/paketo-buildpacks/mri/blob/9e6f6714632a8b488d4ac9a107f8872887ec93b9/build.go#L179)):

```
mriLayer.SharedEnv.Default("MALLOC_ARENA_MAX", 2)
```

This would look very similar to [how we set `GEM_PATH`](https://github.com/paketo-buildpacks/mri/blob/9e6f6714632a8b488d4ac9a107f8872887ec93b9/build.go#L179) - and would be in the same place in the code, too.

I'd also update the unit tests in [build_test.go](https://github.com/paketo-buildpacks/mri/blob/9e6f6714632a8b488d4ac9a107f8872887ec93b9/build_test.go#L144-L146) to look something like:

```
		Expect(layer.SharedEnv).To(Equal(packit.Environment{
                        "MALLOC_ARENA_MAX.default": 2,
			"GEM_PATH.override": "/some/mri/gems/path",
		}))
```

Finally, I'd update the [integration tests](https://github.com/paketo-buildpacks/mri/blob/9e6f6714632a8b488d4ac9a107f8872887ec93b9/integration/logging_test.go#L85-L93) to look something like:

```
			Expect(logs).To(ContainLines(
				"  Configuring build environment",
				MatchRegexp(fmt.Sprintf(`    GEM_PATH         -> "/home/cnb/.gem/ruby/2\.7\.\d+:/layers/%s/mri/lib/ruby/gems/2\.7\.\d+"`, strings.ReplaceAll(settings.Buildpack.ID, "/", "_"))),
				`    MALLOC_ARENA_MAX -> "2",`
			))


			Expect(logs).To(ContainLines(
				"  Configuring launch environment",
				MatchRegexp(fmt.Sprintf(`    GEM_PATH         -> "/home/cnb/.gem/ruby/2\.7\.\d+:/layers/%s/mri/lib/ruby/gems/2\.7\.\d+"`, strings.ReplaceAll(settings.Buildpack.ID, "/", "_"))),
				`    MALLOC_ARENA_MAX -> "2",`
			))
```

With the integration tests, I'd double-check the whitespace. It's easy to miscount the number of spaces and it can be frustrating when the test looks correct but you're actually off by a few spaces 😄

**Comment by robdimsdale** [comment]
Another thought, @fgrehm - if you're using Ruby in production would you prefer to use [`jemalloc`](https://github.com/jemalloc/jemalloc) if it were available (in buildpack form)?

I took a quick look and I don't see any technical (or licensing) blockers to creating a buildpack which provides `jemalloc` and incorporating it into the ruby buildpack order group.

However, evaluating and creating such a buildpack isn't a top priority for the Paketo team at this time. This would be a great opportunity for someone in the wider community to contribute a significant amount to the Paketo project.

If you're interested, we can certainly walk you though the process of submitting and RFC as well as creating a new buildpack.

Either way, we can (collectively) implement the `MALLOC_ARENA_MAX` flag described above.

**Comment by fgrehm** [comment]
Hey @robdimsdale! Yeah, `jemalloc` is awesome, we used it for a while in our development environments but switched to "regular ruby" not long ago. I haven't used in production yet though.

I've shared your message with my team and asked for thoughts, do you think it also makes sense to start a thread in paketo's #ruby and see if others have experience with that in prod? Depending on the interest we can move the discussion to a new issue :smile:

**Comment by robdimsdale** [comment]
> do you think it also makes sense to start a thread in paketo's #ruby and see if others have experience with that in prod?

Sure - I'll put a message in slack.

>  Depending on the interest we can move the discussion to a new issue 

Yes, for sure. If there's any interest we should create a separate issue. I just wanted to tack it on here for an initial conversation while I was investigating alternatives to `MALLOC_ARENA_MAX`

**Comment by fgrehm** [comment]
Heads up: I started working on this late yesterday :v: 

For future ref: [here's the slack thread](https://paketobuildpacks.slack.com/archives/CURGNPSTE/p1666628367335909), we haven't received any replies yet but this should make it more discoverable
