### ISSUE TITLE
Build fails with "max depth exceeded"

### ISSUE THREAD

**Issue by thedarkside** [paketo-buildpacks/ruby#822]
## Expected Behavior
Build succeeds like it have been up until recently

## Current Behavior
Since some days the build fails during image layer download with this message:

```
Building Cloud Native Buildpack-based application with builder paketobuildpacks/builder:full...
full: Pulling from paketobuildpacks/builder
415e3fde5bca: Pulling fs layer
d08d3c1e32f0: Pulling fs layer
15de52ae9c9d: Pulling fs layer
<snip>
607425cbcd39: Pull complete
7d9dccdc2e67: Verifying Checksum
7d9dccdc2e67: Download complete
88b7955b77ba: Pull complete
7d9dccdc2e67: Pull complete
Digest: sha256:077d819956695e51719c020e3063014f5e564044e699913f87b72d898421f818
Status: Downloaded newer image for paketobuildpacks/ruby@sha256:077d819956695e51719c020e3063014f5e564044e699913f87b72d898421f818
ERROR: failed to build: failed to write image to the following tags: [pack.local/builder/6e777974666c72687072:latest: loading image "pack.local/builder/6e777974666c72687072:latest". first error: embedded daemon response: max depth exceeded]
```

We've added only one additional buildpack: fagiani/apt. 

## Possible Solution
I am not sure. Maybe it's related to https://github.com/spring-projects/spring-boot/issues/31233

## Steps to Reproduce
Just try to build a RoR project.

**Comment by thedarkside** [comment]
The build succeeds if i pin the builder to `paketobuildpacks/builder:0.2.152-full`.

**Comment by sophiewigmore** [comment]
@thedarkside this is definitely an issue with the builder containing too many layers rather than the buildpack itself. The spring issue you mentioned is exactly the problem. I'd definitely recommend one of the workarounds mentioned there, specifically using the `buildpackless-builder` could be your best bet.

**Comment by robdimsdale** [comment]
I'm going to close this issue as it's not actionable at the ruby buildpack level and we already have other workarounds (using the buildpackless-builder) and potential avenues we could explore to resolve this problem (maintain a ruby language-specific builder).
